---
# tasks file for roles/nginx

- name: start nginx server
  apt:
    name: nginx
    state: present

- name: change configuration file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-enabled/default"

- name: Change configuration file
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: vagrant
    group: vagrant
  notify: reload_nginx

- name: Create symbolic link
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link

- name: Started nginx service
  service:
    name: nginx
    state: started

- name: flush handlers
  meta: flush_handlers


